exports.access = {
    channelId: {
        notAvailable:       0,
        keyboard:           1,
        blockchainEthereum: 2,
        facebook:           3,
        linkedIn:           4,
        google:             5,
        paypal:             6,
        twitter:            7,
    },
    channelName: {
        notAvailable:       "N/A",
        keyboard:           "KEYBOARD",
        blockchainEthereum: "BLOCKCHAIN_ETHEREUM",
        facebook:           "FACEBOOK",
        linkedIn:           "LINKEDIN",
        google:             "GOOGLE",
        paypal:             "PAYPAL",
        twitter:            "TWITTER",
    },
    accessName: {
        username:           "USERNAME",
        password:           "PASSWORD",
        ethAddress:         "ETH_ADDRESS",
        facebookUserId:     "FACEBOOK_USER_ID",
        linkedInUserId:     "LINKEDIN_USER_ID",
        googleUserId:       "GOOGLE_USER_ID",
        twitterUserId:      "TWITTER_USER_ID",
    },
};