exports.messageBook = {
    successMessage: {
        SUCCESS:                            {code:200,message:"OK"},
    },
    errorMessage: {
        INTERNAL_UNKNOWN:                   {code:500,message:"Internal server error (#0000)"},
        INTERNAL_AUTHENTICATION:            {code:500,message:"Internal server error (#3135)"},
        INTERNAL_FACEBOOK_VALIDATE_TOKEN:   {code:500,message:"Internal server error (#2647)"},
        INTERNAL_LINKEDIN_VALIDATING_TOKEN: {code:500,message:"Internal server error (#3237)"},
        INTERNAL_LINKEDIN_FETCHING_DATA:    {code:500,message:"Internal server error (#9463)"},
        INTERNAL_GOOGLE_VALIDATING_TOKEN:   {code:500,message:"Internal server error (#7410)"},
        INTERNAL_GOOGLE_FETCHING_DATA:      {code:500,message:"Internal server error (#3642)"},
        INTERNAL_TWITTER_VALIDATING_TOKEN:  {code:500,message:"Internal server error (#1313)"},
        INTERNAL_TWITTER_FETCHING_DATA:     {code:500,message:"Internal server error (#3131)"},
        INTERNAL_VERIFY_MIDDLEWARE:         {code:500,message:"Internal server error (#8441)"},
        ENDPOINT_NOT_FOUND:                 {code:500,message:"Internal server error (#9746)"},
        HASHING_ERROR:                      {code:500,message:"Internal server error (#7496)"},
        HASH_VERIFICATION_ERROR:            {code:500,message:"Internal server error (#8502)"},
        DB_ERROR:                           {code:500,message:"Internal server error (#9761)"},
        DB_SQL_ERROR:                       {code:500,message:"Internal server error (#9763)"},
        DB_ELEMENT_NOT_FOUND:               {code:500,message:"Internal server error (#1024)"},
        ERROR_STORING_USER_DETAILS:         {code:500,message:"Internal server error (#9638)"},
        NO_THRUBI_PRICE_SILVER:             {code:500,message:"Internal server error (#5432)"},
        NO_THRUBI_PRICE_SILVER_NEXT:        {code:500,message:"Internal server error (#5784)"},
        DECLARE_INCOME_ERROR:               {code:500,message:"Internal server error (#5136)"},
        DISTRIBUTE_THRUBI_ERROR:            {code:500,message:"Internal server error (#5978)"},
        TRANSFORM_ERROR:                    {code:500,message:"Internal server error (#5635)"},
        AWARD_ERROR:                        {code:500,message:"Internal server error (#5741)"},
        CLAIM_ERROR:                        {code:500,message:"Internal server error (#5529)"},
        REF_ERROR:                          {code:500,message:"Internal server error (#8879)"},
        EXRATE_FETCH_ERROR_INTERNAL:        {code:500,message:"Internal server error (#1136)"},
        CHANGE_CONFIG_ERROR:                {code:500,message:"Internal server error (#2011)"},
        TOO_MANY_SUGGESTIONS:               {code:401,message:"Daily suggestion queue filled, please submit to info@thrubi.org. Thank you!"},
        ACTION_NOT_FOUND:                   {code:401,message:"Action not found"},
        CANNOT_UPDATE_DOCUMENT_MANUALLY:    {code:401,message:"Not allowed: attempted to update user document manually"},
        EMAIL_NOT_VERIFIED:                 {code:401,message:"Please verify your email address in order to activate your account"},
        EMAIL_LINK_EXPIRED:                 {code:403,message:"Link expired. Please enter your email again in your profile section."},
        INCOME_NOT_APPROVED:                {code:401,message:"Your income needs to be approved in order to activate your account"},
        ACCOUNT_CLOSED:                     {code:401,message:"This user account has been closed"},
        ACCOUNT_DEACTIVATED:                {code:401,message:"This user account is currently deactivated"},
        UNACCEPTABLE_DEACTIVATION_CODE:     {code:401,message:"Provided activation code is unacceptable"},
        NOT_AUTHORIZED_USERDATA_SPIKE:      {code:401,message:"User not authorized: spike detected"},
        NOT_AUTHORIZED:                     {code:401,message:"User not authorized"},
        WRONG_PASSWORD:                     {code:403,message:"Wrong password"},
        FORBIDDEN:                          {code:403,message:"Forbidden"},
        USER_NOT_FOUND:                     {code:404,message:"User not found. New to Thrubi? Try creating a new Thrubi account!"},
        EXRATE_FETCH_ERROR:                 {code:404,message:"Error fetching exchange rate"},
        NOT_A_PAY_CHANNEL:                  {code:400,message:"Channel is not for payment"},
        CHANNEL_NOT_AVAILABLE:              {code:400,message:"This payment method is not available, try adding it first!"},
        ACCESS_VALUE_TAKEN:                 {code:400,message:"Your login credentials are already associated to a Thrubi user. Try logging in!"},
        PROFILE_PICTURE_TOO_BIG:            {code:403,message:"The profile picture size is beyond the accepted limit"},
        PROFILE_PICTURE_TOO_MANY:           {code:403,message:"Profile picture upload limit reached, please contact support"},
        USER_ONLY_HAS_ONE_CHANNEL:          {code:403,message:"We cannot remove your only login method"},
        USER_LOGGED_OUT:                    {code:404,message:"User logged out"},
        MODIFIED_JWT:                       {code:401,message:"We could not verify your access credentials"},
        MODIFIED_HASH:                      {code:401,message:"Modified hash"},
        ETH_ADDRESS_NOT_OWN:                {code:403,message:"We cannot prove you own this Ethereum address"},
        INVALID_REFRESH_TOKEN:              {code:401,message:"Authorization error: refresh token invalid"},
        INVALID_FACEBOOK_USER_TOKEN:        {code:401,message:"Facebook token not valid"},
        EMPTY_FACEBOOK_USER_TOKEN:          {code:401,message:"No Facebook token provided"},
        INVALID_LINKEDIN_CODE:              {code:401,message:"LinkedIn code not valid"},
        EMPTY_LINKEDIN_CODE:                {code:401,message:"LinkedIn code not provided"},
        EMPTY_LINKEDIN_USER_ACCESS_TOKEN:   {code:401,message:"Empty LinkedIn user access token"},
        INVALID_GOOGLE_CODE:                {code:401,message:"Google code not valid"},
        EMPTY_GOOGLE_CODE:                  {code:401,message:"Google code not provided"},
        EMPTY_GOOGLE_USER_ACCESS_TOKEN:     {code:401,message:"Empty Google user access token"},
        INVALID_TWITTER_TOKEN_OR_VERIFIER:  {code:401,message:"Twitter access code or verifier not valid"},
        EMPTY_TWITTER_TOKEN_OR_VERIFIER:    {code:401,message:"Twitter access code or verifier not provided"},
        EMPTY_TWITTER_USER_ACCESS_TOKEN:    {code:401,message:"Empty Twitter user access token"},
    },
};