exports.THRUBI_BLUE_MODE = 1;
exports.THRUBI_SILVER_MODE = 10;

exports.THRUBI_USER_ACTIVATED = 0;
exports.THRUBI_USER_DEACTIVATED = 1;

exports.THRUBI_ROLE_USER = 0;
exports.THRUBI_ROLE_ADMIN = 1;