exports.user = {
    actionType: {
        nonAuth: {
            CLICK_CHANNEL:       {
                actionType: "CLICK_CHANNEL",
                actionValue: {
                    LOGIN_TWITTER:                 "LOGIN_TWITTER",
                    SIGNUP_TWITTER:                "SIGNUP_TWITTER",
                    UPDATE_TWITTER:                "UPDATE_TWITTER",
                    DELETE_TWITTER:                "DELETE_TWITTER",
                    ADD_TWITTER:                   "ADD_TWITTER",
                    LOGIN_FACEBOOK:                "LOGIN_FACEBOOK",
                    SIGNUP_FACEBOOK:               "SIGNUP_FACEBOOK",
                    UPDATE_FACEBOOK:               "UPDATE_FACEBOOK",
                    DELETE_FACEBOOK:               "DELETE_FACEBOOK",
                    ADD_FACEBOOK:                  "ADD_FACEBOOK",
                    LOGIN_GOOGLE:                  "LOGIN_GOOGLE",
                    SIGNUP_GOOGLE:                 "SIGNUP_GOOGLE",
                    UPDATE_GOOGLE:                 "UPDATE_GOOGLE",
                    DELETE_GOOGLE:                 "DELETE_GOOGLE",
                    ADD_GOOGLE:                    "ADD_GOOGLE",
                    LOGIN_LINKEDIN:                "LOGIN_LINKEDIN",
                    SIGNUP_LINKEDIN:               "SIGNUP_LINKEDIN",
                    UPDATE_LINKEDIN:               "UPDATE_LINKEDIN",
                    DELETE_LINKEDIN:               "DELETE_LINKEDIN",
                    ADD_LINKEDIN:                  "ADD_LINKEDIN",
                    LOGIN_BLOCKCHAIN_ETHEREUM:     "LOGIN_BLOCKCHAIN_ETHEREUM",
                    SIGNUP_BLOCKCHAIN_ETHEREUM:    "SIGNUP_BLOCKCHAIN_ETHEREUM",
                    UPDATE_BLOCKCHAIN_ETHEREUM:    "UPDATE_BLOCKCHAIN_ETHEREUM",
                    DELETE_BLOCKCHAIN_ETHEREUM:    "DELETE_BLOCKCHAIN_ETHEREUM",
                    ADD_BLOCKCHAIN_ETHEREUM:       "ADD_BLOCKCHAIN_ETHEREUM",
                    LOGIN_PAYPAL:                  "LOGIN_PAYPAL",
                    SIGNUP_PAYPAL:                 "SIGNUP_PAYPAL",
                    UPDATE_PAYPAL:                 "UPDATE_PAYPAL",
                    DELETE_PAYPAL:                 "DELETE_PAYPAL",
                    ADD_PAYPAL:                    "ADD_PAYPAL",
                    LOGIN_KEYBOARD:                "LOGIN_KEYBOARD",
                    SIGNUP_KEYBOARD:               "SIGNUP_KEYBOARD",
                    UPDATE_KEYBOARD:               "UPDATE_KEYBOARD",
                    DELETE_KEYBOARD:               "DELETE_KEYBOARD",
                    ADD_KEYBOARD:                  "ADD_KEYBOARD",
                }
            },
            CLICK_GUEST_MENU:     {
                actionType: "CLICK_GUEST_MENU",
                actionValue: {
                    HOME:           "HOME",
                    USER:           "USER",
                    VISION:         "VISION",
                    FAQ:            "FAQ",
                    INFOGRAPHICS:   "INFOGRAPHICS",
                    BLOG:           "BLOG",
                    CONTACT:        "CONTACT",
                },
            },
            CLICK_FAQ:    {
                actionType: "CLICK_FAQ",
                actionValue: {
                    VISION_IDENTITY:            "VISION_IDENTITY",
                    VISION_INCOME_DISCLOSE:     "VISION_INCOME_DISCLOSE",
                    VISION_INCOME_VERIFY:       "VISION_INCOME_VERIFY",
                    VISION_INCOME_FRAUD:        "VISION_INCOME_FRAUD",
                    VISION_UBI_MONTHLY:         "VISION_UBI_MONTHLY",
                    VISION_TAX_HAVENS:          "VISION_TAX_HAVENS",
                    WEALTHY_GOLD:               "WEALTHY_GOLD",
                    WEALTHY_COMPANY:            "WEALTHY_COMPANY",
                    WEALTHY_WORLDWIDE:          "WEALTHY_WORLDWIDE",
                    WEALTHY_PUBLIC_INFO:        "WEALTHY_PUBLIC_INFO",
                    WEALTHY_BUSINESS_MODEL:     "WEALTHY_BUSINESS_MODEL",
                    SOCIETIES_THRUBI_WHY:       "SOCIETIES_THRUBI_WHY",
                    SOCIETIES_UBI_GOV:          "SOCIETIES_UBI_GOV",
                    SOCIETIES_MODELS_PUBLIC:    "SOCIETIES_MODELS_PUBLIC",
                    SOCIETIES_GOV_CONTRIBUTE:   "SOCIETIES_GOV_CONTRIBUTE",
                    SOCIETIES_MODELS_ABOUT:     "SOCIETIES_MODELS_ABOUT",
                    SOCIETIES_FLAT_UBI:         "SOCIETIES_FLAT_UBI",
                },
            },
        },
        auth: {

        },
    },
    detailName: {
        name:               "name",
        surname:            "surname",
        email:              "email",
        document:           "document",
        submittedDocument:  "submittedDocument",
        profilePicture:     "profilePicture",
        profilePictureOld:  "profilePictureOld",
    },
    flags: {
        deactivated:        "deactivated",
        emailVerified:      "email_verified",
        identityCertified:  "identity_certified",
        incomeApproved:     "income_approved",
    },
    flagStatus: {
        true:        1,
        false:       0,
        pending:    -1,
    },
    identityCertification: {
        passportPrefix: "passport#ID01234.",
        timeout: 5000,
    },
    incomeApproval: {
        timeout: 5000,
    },
    activationState: {
        activated:              0,
        deactivated: {
            userRequest:        1,
            changedEmail:       10,
            submittedDocument:  11,
            leftPopulation:     12,
            declaredTaxNumber:  13,
            declaredIncome:     14,
        },
    }
};