INSERT INTO ccy VALUES ('N/A','Not Available','n/a') ON DUPLICATE KEY UPDATE ccy_symbol='n/a', ccy_name='Not Available';
INSERT INTO ccy VALUES ('BTC','Bitcoin','₿') ON DUPLICATE KEY UPDATE ccy_symbol='₿', ccy_name='Bitcoin';
INSERT INTO ccy VALUES ('XRP','Ripples','XRP') ON DUPLICATE KEY UPDATE ccy_symbol='XRP', ccy_name='Ripples';
INSERT INTO ccy VALUES ('XMR','Monero','ɱ') ON DUPLICATE KEY UPDATE ccy_symbol='ɱ', ccy_name='Monero';
INSERT INTO ccy VALUES ('LTC','Litecoin','Ł') ON DUPLICATE KEY UPDATE ccy_symbol='Ł', ccy_name='Litecoin';
INSERT INTO ccy VALUES ('ETH','Ethereum','Ξ') ON DUPLICATE KEY UPDATE ccy_symbol='Ξ', ccy_name='Ethereum';
INSERT INTO ccy VALUES ('CYP','Cypriot Pound','CYP') ON DUPLICATE KEY UPDATE ccy_symbol='CYP', ccy_name='Cypriot Pound';
INSERT INTO ccy VALUES ('EEK','Estonian Kroon','EEK') ON DUPLICATE KEY UPDATE ccy_symbol='EEK', ccy_name='Estonian Kroon';
INSERT INTO ccy VALUES ('MTL','Maltese Lira','MTL') ON DUPLICATE KEY UPDATE ccy_symbol='MTL', ccy_name='Maltese Lira';
INSERT INTO ccy VALUES ('SIT','Slovenian Tolar','SIT') ON DUPLICATE KEY UPDATE ccy_symbol='SIT', ccy_name='Slovenian Tolar';
INSERT INTO ccy VALUES ('SKK','Slovak Koruna','SKK') ON DUPLICATE KEY UPDATE ccy_symbol='SKK', ccy_name='Slovak Koruna';

INSERT INTO ccy VALUES ('AFN','Afghan afghani','؋') ON DUPLICATE KEY UPDATE ccy_symbol='؋', ccy_name='Afghan afghani';
INSERT INTO ccy VALUES ('ALL','Albanian lek','L') ON DUPLICATE KEY UPDATE ccy_symbol='L', ccy_name='Albanian lek';
INSERT INTO ccy VALUES ('DZD','Algerian dinar','دج') ON DUPLICATE KEY UPDATE ccy_symbol='دج', ccy_name='Algerian dinar';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('AOA','Angolan kwanza','Kz') ON DUPLICATE KEY UPDATE ccy_symbol='Kz', ccy_name='Angolan kwanza';
INSERT INTO ccy VALUES ('XCD','Eastern Caribbean dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Eastern Caribbean dollar';
INSERT INTO ccy VALUES ('XCD','Eastern Caribbean dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Eastern Caribbean dollar';
INSERT INTO ccy VALUES ('ARS','Argentine peso','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Argentine peso';
INSERT INTO ccy VALUES ('AMD','Armenian dram','֏') ON DUPLICATE KEY UPDATE ccy_symbol='֏', ccy_name='Armenian dram';
INSERT INTO ccy VALUES ('_A_','Artsakh dram','դր.') ON DUPLICATE KEY UPDATE ccy_symbol='դր.', ccy_name='Artsakh dram';
INSERT INTO ccy VALUES ('AWG','Aruban florin','ƒ') ON DUPLICATE KEY UPDATE ccy_symbol='ƒ', ccy_name='Aruban florin';
INSERT INTO ccy VALUES ('SHP','Saint Helena pound','£') ON DUPLICATE KEY UPDATE ccy_symbol='£', ccy_name='Saint Helena pound';
INSERT INTO ccy VALUES ('AUD','Australian dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Australian dollar';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('AZN','Azerbaijani manat','₼') ON DUPLICATE KEY UPDATE ccy_symbol='₼', ccy_name='Azerbaijani manat';
INSERT INTO ccy VALUES ('BSD','Bahamian dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Bahamian dollar';
INSERT INTO ccy VALUES ('BHD','Bahraini dinar','.د.ب') ON DUPLICATE KEY UPDATE ccy_symbol='.د.ب', ccy_name='Bahraini dinar';
INSERT INTO ccy VALUES ('BDT','Bangladeshi taka','৳') ON DUPLICATE KEY UPDATE ccy_symbol='৳', ccy_name='Bangladeshi taka';
INSERT INTO ccy VALUES ('BBD','Barbadian dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Barbadian dollar';
INSERT INTO ccy VALUES ('BYN','Belarusian ruble','Br') ON DUPLICATE KEY UPDATE ccy_symbol='Br', ccy_name='Belarusian ruble';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('BZD','Belize dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Belize dollar';
INSERT INTO ccy VALUES ('XOF','West African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='West African CFA franc';
INSERT INTO ccy VALUES ('BMD','Bermudian dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Bermudian dollar';
INSERT INTO ccy VALUES ('BTN','Bhutanese ngultrum','Nu.') ON DUPLICATE KEY UPDATE ccy_symbol='Nu.', ccy_name='Bhutanese ngultrum';
INSERT INTO ccy VALUES ('BOB','Bolivian boliviano','Bs.') ON DUPLICATE KEY UPDATE ccy_symbol='Bs.', ccy_name='Bolivian boliviano';
INSERT INTO ccy VALUES ('USD','United States dollar[H]','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar[H]';
INSERT INTO ccy VALUES ('BAM','Bosnia and Herzegovina convertible mark','КМ') ON DUPLICATE KEY UPDATE ccy_symbol='КМ', ccy_name='Bosnia and Herzegovina convertible mark';
INSERT INTO ccy VALUES ('BWP','Botswana pula','P') ON DUPLICATE KEY UPDATE ccy_symbol='P', ccy_name='Botswana pula';
INSERT INTO ccy VALUES ('BRL','Brazilian real','R$') ON DUPLICATE KEY UPDATE ccy_symbol='R$', ccy_name='Brazilian real';
INSERT INTO ccy VALUES ('USD','United States dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar';
INSERT INTO ccy VALUES ('USD','United States dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar';
INSERT INTO ccy VALUES ('BND','Brunei dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Brunei dollar';
INSERT INTO ccy VALUES ('BGN','Bulgarian lev','лв.') ON DUPLICATE KEY UPDATE ccy_symbol='лв.', ccy_name='Bulgarian lev';
INSERT INTO ccy VALUES ('XOF','West African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='West African CFA franc';
INSERT INTO ccy VALUES ('BIF','Burundian franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='Burundian franc';
INSERT INTO ccy VALUES ('KHR','Cambodian riel','៛') ON DUPLICATE KEY UPDATE ccy_symbol='៛', ccy_name='Cambodian riel';
INSERT INTO ccy VALUES ('XAF','Central African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='Central African CFA franc';
INSERT INTO ccy VALUES ('CAD','Canadian dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Canadian dollar';
INSERT INTO ccy VALUES ('CVE','Cape Verdean escudo','Esc$') ON DUPLICATE KEY UPDATE ccy_symbol='Esc$', ccy_name='Cape Verdean escudo';
INSERT INTO ccy VALUES ('KYD','Cayman Islands dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Cayman Islands dollar';
INSERT INTO ccy VALUES ('XAF','Central African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='Central African CFA franc';
INSERT INTO ccy VALUES ('XAF','Central African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='Central African CFA franc';
INSERT INTO ccy VALUES ('CLP','Chilean peso','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Chilean peso';
INSERT INTO ccy VALUES ('CNY','Chinese yuan','元') ON DUPLICATE KEY UPDATE ccy_symbol='元', ccy_name='Chinese yuan';
INSERT INTO ccy VALUES ('COP','Colombian peso','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Colombian peso';
INSERT INTO ccy VALUES ('KMF','Comorian franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='Comorian franc';
INSERT INTO ccy VALUES ('CDF','Congolese franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='Congolese franc';
INSERT INTO ccy VALUES ('XAF','Central African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='Central African CFA franc';
INSERT INTO ccy VALUES ('CKD','Cook Islands dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Cook Islands dollar';
INSERT INTO ccy VALUES ('CRC','Costa Rican colón','₡') ON DUPLICATE KEY UPDATE ccy_symbol='₡', ccy_name='Costa Rican colón';
INSERT INTO ccy VALUES ('XOF','West African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='West African CFA franc';
INSERT INTO ccy VALUES ('HRK','Croatian kuna','kn') ON DUPLICATE KEY UPDATE ccy_symbol='kn', ccy_name='Croatian kuna';
INSERT INTO ccy VALUES ('CUP','Cuban peso','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Cuban peso';
INSERT INTO ccy VALUES ('CUC','Cuban convertible peso','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Cuban convertible peso';
INSERT INTO ccy VALUES ('ANG','Netherlands Antillean guilder','ƒ') ON DUPLICATE KEY UPDATE ccy_symbol='ƒ', ccy_name='Netherlands Antillean guilder';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('CZK','Czech koruna','Kč') ON DUPLICATE KEY UPDATE ccy_symbol='Kč', ccy_name='Czech koruna';
INSERT INTO ccy VALUES ('DKK','Danish krone','kr') ON DUPLICATE KEY UPDATE ccy_symbol='kr', ccy_name='Danish krone';
INSERT INTO ccy VALUES ('DJF','Djiboutian franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='Djiboutian franc';
INSERT INTO ccy VALUES ('XCD','Eastern Caribbean dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Eastern Caribbean dollar';
INSERT INTO ccy VALUES ('DOP','Dominican peso','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Dominican peso';
INSERT INTO ccy VALUES ('USD','United States dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar';
INSERT INTO ccy VALUES ('USD','United States dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar';
INSERT INTO ccy VALUES ('EGP','Egyptian pound','ج.م') ON DUPLICATE KEY UPDATE ccy_symbol='ج.م', ccy_name='Egyptian pound';
INSERT INTO ccy VALUES ('USD','United States dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar';
INSERT INTO ccy VALUES ('XAF','Central African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='Central African CFA franc';
INSERT INTO ccy VALUES ('ERN','Eritrean nakfa','Nfk') ON DUPLICATE KEY UPDATE ccy_symbol='Nfk', ccy_name='Eritrean nakfa';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('SZL','Swazi lilangeni','L') ON DUPLICATE KEY UPDATE ccy_symbol='L', ccy_name='Swazi lilangeni';
INSERT INTO ccy VALUES ('ETB','Ethiopian birr','Br') ON DUPLICATE KEY UPDATE ccy_symbol='Br', ccy_name='Ethiopian birr';
INSERT INTO ccy VALUES ('FKP','Falkland Islands pound','£') ON DUPLICATE KEY UPDATE ccy_symbol='£', ccy_name='Falkland Islands pound';
INSERT INTO ccy VALUES ('DKK','Danish krone','kr') ON DUPLICATE KEY UPDATE ccy_symbol='kr', ccy_name='Danish krone';
INSERT INTO ccy VALUES ('FOK','Faroese króna','kr') ON DUPLICATE KEY UPDATE ccy_symbol='kr', ccy_name='Faroese króna';
INSERT INTO ccy VALUES ('FJD','Fijian dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Fijian dollar';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('XPF','CFP franc','₣') ON DUPLICATE KEY UPDATE ccy_symbol='₣', ccy_name='CFP franc';
INSERT INTO ccy VALUES ('XAF','Central African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='Central African CFA franc';
INSERT INTO ccy VALUES ('GMD','Gambian dalasi','D') ON DUPLICATE KEY UPDATE ccy_symbol='D', ccy_name='Gambian dalasi';
INSERT INTO ccy VALUES ('GEL','Georgian lari','₾') ON DUPLICATE KEY UPDATE ccy_symbol='₾', ccy_name='Georgian lari';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('GHS','Ghanaian cedi','₵') ON DUPLICATE KEY UPDATE ccy_symbol='₵', ccy_name='Ghanaian cedi';
INSERT INTO ccy VALUES ('GIP','Gibraltar pound','£') ON DUPLICATE KEY UPDATE ccy_symbol='£', ccy_name='Gibraltar pound';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('XCD','Eastern Caribbean dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Eastern Caribbean dollar';
INSERT INTO ccy VALUES ('GTQ','Guatemalan quetzal','Q') ON DUPLICATE KEY UPDATE ccy_symbol='Q', ccy_name='Guatemalan quetzal';
INSERT INTO ccy VALUES ('GGP','Guernsey pound','£') ON DUPLICATE KEY UPDATE ccy_symbol='£', ccy_name='Guernsey pound';
INSERT INTO ccy VALUES ('GNF','Guinean franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='Guinean franc';
INSERT INTO ccy VALUES ('XOF','West African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='West African CFA franc';
INSERT INTO ccy VALUES ('GYD','Guyanese dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Guyanese dollar';
INSERT INTO ccy VALUES ('HTG','Haitian gourde','G') ON DUPLICATE KEY UPDATE ccy_symbol='G', ccy_name='Haitian gourde';
INSERT INTO ccy VALUES ('HNL','Honduran lempira','L') ON DUPLICATE KEY UPDATE ccy_symbol='L', ccy_name='Honduran lempira';
INSERT INTO ccy VALUES ('HKD','Hong Kong dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Hong Kong dollar';
INSERT INTO ccy VALUES ('HUF','Hungarian forint','Ft') ON DUPLICATE KEY UPDATE ccy_symbol='Ft', ccy_name='Hungarian forint';
INSERT INTO ccy VALUES ('ISK','Icelandic króna','Íkr') ON DUPLICATE KEY UPDATE ccy_symbol='Íkr', ccy_name='Icelandic króna';
INSERT INTO ccy VALUES ('INR','Indian rupee','₹') ON DUPLICATE KEY UPDATE ccy_symbol='₹', ccy_name='Indian rupee';
INSERT INTO ccy VALUES ('IDR','Indonesian rupiah','Rp') ON DUPLICATE KEY UPDATE ccy_symbol='Rp', ccy_name='Indonesian rupiah';
INSERT INTO ccy VALUES ('IRR','Iranian rial','﷼') ON DUPLICATE KEY UPDATE ccy_symbol='﷼', ccy_name='Iranian rial';
INSERT INTO ccy VALUES ('IQD','Iraqi dinar','ع.د') ON DUPLICATE KEY UPDATE ccy_symbol='ع.د', ccy_name='Iraqi dinar';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('IMP','Manx pound','£') ON DUPLICATE KEY UPDATE ccy_symbol='£', ccy_name='Manx pound';
INSERT INTO ccy VALUES ('ILS','Israeli new shekel','₪') ON DUPLICATE KEY UPDATE ccy_symbol='₪', ccy_name='Israeli new shekel';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('JMD','Jamaican dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Jamaican dollar';
INSERT INTO ccy VALUES ('JPY','Japanese yen','¥') ON DUPLICATE KEY UPDATE ccy_symbol='¥', ccy_name='Japanese yen';
INSERT INTO ccy VALUES ('JEP','Jersey pound','£') ON DUPLICATE KEY UPDATE ccy_symbol='£', ccy_name='Jersey pound';
INSERT INTO ccy VALUES ('JOD','Jordanian dinar','د.ا') ON DUPLICATE KEY UPDATE ccy_symbol='د.ا', ccy_name='Jordanian dinar';
INSERT INTO ccy VALUES ('KZT','Kazakhstani tenge','₸') ON DUPLICATE KEY UPDATE ccy_symbol='₸', ccy_name='Kazakhstani tenge';
INSERT INTO ccy VALUES ('KES','Kenyan shilling','Sh') ON DUPLICATE KEY UPDATE ccy_symbol='Sh', ccy_name='Kenyan shilling';
INSERT INTO ccy VALUES ('KID','Kiribati dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Kiribati dollar';
INSERT INTO ccy VALUES ('KPW','North Korean won','₩') ON DUPLICATE KEY UPDATE ccy_symbol='₩', ccy_name='North Korean won';
INSERT INTO ccy VALUES ('KRW','South Korean won','₩') ON DUPLICATE KEY UPDATE ccy_symbol='₩', ccy_name='South Korean won';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('KWD','Kuwaiti dinar','د.ك') ON DUPLICATE KEY UPDATE ccy_symbol='د.ك', ccy_name='Kuwaiti dinar';
INSERT INTO ccy VALUES ('KGS','Kyrgyzstani som','с') ON DUPLICATE KEY UPDATE ccy_symbol='с', ccy_name='Kyrgyzstani som';
INSERT INTO ccy VALUES ('LAK','Lao kip','₭') ON DUPLICATE KEY UPDATE ccy_symbol='₭', ccy_name='Lao kip';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('LBP','Lebanese pound','ل.ل.‎') ON DUPLICATE KEY UPDATE ccy_symbol='ل.ل.‎', ccy_name='Lebanese pound';
INSERT INTO ccy VALUES ('LSL','Lesotho loti','L') ON DUPLICATE KEY UPDATE ccy_symbol='L', ccy_name='Lesotho loti';
INSERT INTO ccy VALUES ('LRD','Liberian dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Liberian dollar';
INSERT INTO ccy VALUES ('LYD','Libyan dinar','ل.د') ON DUPLICATE KEY UPDATE ccy_symbol='ل.د', ccy_name='Libyan dinar';
INSERT INTO ccy VALUES ('CHF','Swiss franc','Fr.') ON DUPLICATE KEY UPDATE ccy_symbol='Fr.', ccy_name='Swiss franc';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('MOP','Macanese pataca','P') ON DUPLICATE KEY UPDATE ccy_symbol='P', ccy_name='Macanese pataca';
INSERT INTO ccy VALUES ('MGA','Malagasy ariary','Ar') ON DUPLICATE KEY UPDATE ccy_symbol='Ar', ccy_name='Malagasy ariary';
INSERT INTO ccy VALUES ('MWK','Malawian kwacha','MK') ON DUPLICATE KEY UPDATE ccy_symbol='MK', ccy_name='Malawian kwacha';
INSERT INTO ccy VALUES ('MYR','Malaysian ringgit','RM') ON DUPLICATE KEY UPDATE ccy_symbol='RM', ccy_name='Malaysian ringgit';
INSERT INTO ccy VALUES ('MVR','Maldivian rufiyaa','.ރ') ON DUPLICATE KEY UPDATE ccy_symbol='.ރ', ccy_name='Maldivian rufiyaa';
INSERT INTO ccy VALUES ('XOF','West African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='West African CFA franc';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('USD','United States dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar';
INSERT INTO ccy VALUES ('MRU','Mauritanian ouguiya','UM') ON DUPLICATE KEY UPDATE ccy_symbol='UM', ccy_name='Mauritanian ouguiya';
INSERT INTO ccy VALUES ('MUR','Mauritian rupee','₨') ON DUPLICATE KEY UPDATE ccy_symbol='₨', ccy_name='Mauritian rupee';
INSERT INTO ccy VALUES ('MXN','Mexican peso','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Mexican peso';
INSERT INTO ccy VALUES ('USD','United States dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar';
INSERT INTO ccy VALUES ('MDL','Moldovan leu','L') ON DUPLICATE KEY UPDATE ccy_symbol='L', ccy_name='Moldovan leu';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('MNT','Mongolian tögrög','₮') ON DUPLICATE KEY UPDATE ccy_symbol='₮', ccy_name='Mongolian tögrög';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('XCD','Eastern Caribbean dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Eastern Caribbean dollar';
INSERT INTO ccy VALUES ('MAD','Moroccan dirham','د.م.') ON DUPLICATE KEY UPDATE ccy_symbol='د.م.', ccy_name='Moroccan dirham';
INSERT INTO ccy VALUES ('MZN','Mozambican metical','MT') ON DUPLICATE KEY UPDATE ccy_symbol='MT', ccy_name='Mozambican metical';
INSERT INTO ccy VALUES ('MMK','Burmese kyat','Ks') ON DUPLICATE KEY UPDATE ccy_symbol='Ks', ccy_name='Burmese kyat';
INSERT INTO ccy VALUES ('NAD','Namibian dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Namibian dollar';
INSERT INTO ccy VALUES ('AUD','Australian dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Australian dollar';
INSERT INTO ccy VALUES ('NPR','Nepalese rupee','रू') ON DUPLICATE KEY UPDATE ccy_symbol='रू', ccy_name='Nepalese rupee';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('XPF','CFP franc','₣') ON DUPLICATE KEY UPDATE ccy_symbol='₣', ccy_name='CFP franc';
INSERT INTO ccy VALUES ('NZD','New Zealand dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='New Zealand dollar';
INSERT INTO ccy VALUES ('NIO','Nicaraguan córdoba','C$') ON DUPLICATE KEY UPDATE ccy_symbol='C$', ccy_name='Nicaraguan córdoba';
INSERT INTO ccy VALUES ('XOF','West African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='West African CFA franc';
INSERT INTO ccy VALUES ('NGN','Nigerian naira','₦') ON DUPLICATE KEY UPDATE ccy_symbol='₦', ccy_name='Nigerian naira';
INSERT INTO ccy VALUES ('NZD','New Zealand dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='New Zealand dollar';
INSERT INTO ccy VALUES ('MKD','Macedonian denar','ден') ON DUPLICATE KEY UPDATE ccy_symbol='ден', ccy_name='Macedonian denar';
INSERT INTO ccy VALUES ('TRY','Turkish lira','₺') ON DUPLICATE KEY UPDATE ccy_symbol='₺', ccy_name='Turkish lira';
INSERT INTO ccy VALUES ('NOK','Norwegian krone','kr') ON DUPLICATE KEY UPDATE ccy_symbol='kr', ccy_name='Norwegian krone';
INSERT INTO ccy VALUES ('OMR','Omani rial','ر.ع.') ON DUPLICATE KEY UPDATE ccy_symbol='ر.ع.', ccy_name='Omani rial';
INSERT INTO ccy VALUES ('PKR','Pakistani rupee','₨') ON DUPLICATE KEY UPDATE ccy_symbol='₨', ccy_name='Pakistani rupee';
INSERT INTO ccy VALUES ('USD','United States dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar';
INSERT INTO ccy VALUES ('ILS','Israeli new shekel','₪') ON DUPLICATE KEY UPDATE ccy_symbol='₪', ccy_name='Israeli new shekel';
INSERT INTO ccy VALUES ('PAB','Panamanian balboa','B/.') ON DUPLICATE KEY UPDATE ccy_symbol='B/.', ccy_name='Panamanian balboa';
INSERT INTO ccy VALUES ('PGK','Papua New Guinean kina','K') ON DUPLICATE KEY UPDATE ccy_symbol='K', ccy_name='Papua New Guinean kina';
INSERT INTO ccy VALUES ('PYG','Paraguayan guaraní','₲') ON DUPLICATE KEY UPDATE ccy_symbol='₲', ccy_name='Paraguayan guaraní';
INSERT INTO ccy VALUES ('PEN','Peruvian sol','S/.') ON DUPLICATE KEY UPDATE ccy_symbol='S/.', ccy_name='Peruvian sol';
INSERT INTO ccy VALUES ('PHP','Philippine peso','₱') ON DUPLICATE KEY UPDATE ccy_symbol='₱', ccy_name='Philippine peso';
INSERT INTO ccy VALUES ('NZD','New Zealand dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='New Zealand dollar';
INSERT INTO ccy VALUES ('PND','Pitcairn Islands dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Pitcairn Islands dollar';
INSERT INTO ccy VALUES ('PLN','Polish złoty','zł') ON DUPLICATE KEY UPDATE ccy_symbol='zł', ccy_name='Polish złoty';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('QAR','Qatari riyal','ر.ق') ON DUPLICATE KEY UPDATE ccy_symbol='ر.ق', ccy_name='Qatari riyal';
INSERT INTO ccy VALUES ('RON','Romanian leu','lei') ON DUPLICATE KEY UPDATE ccy_symbol='lei', ccy_name='Romanian leu';
INSERT INTO ccy VALUES ('RUB','Russian ruble','₽') ON DUPLICATE KEY UPDATE ccy_symbol='₽', ccy_name='Russian ruble';
INSERT INTO ccy VALUES ('RWF','Rwandan franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='Rwandan franc';
INSERT INTO ccy VALUES ('USD','United States dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar';
INSERT INTO ccy VALUES ('DZD','Algerian dinar','دج') ON DUPLICATE KEY UPDATE ccy_symbol='دج', ccy_name='Algerian dinar';
INSERT INTO ccy VALUES ('_S_','Sahrawi peseta','₧') ON DUPLICATE KEY UPDATE ccy_symbol='₧', ccy_name='Sahrawi peseta';
INSERT INTO ccy VALUES ('SHP','Saint Helena pound','£') ON DUPLICATE KEY UPDATE ccy_symbol='£', ccy_name='Saint Helena pound';
INSERT INTO ccy VALUES ('XCD','Eastern Caribbean dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Eastern Caribbean dollar';
INSERT INTO ccy VALUES ('XCD','Eastern Caribbean dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Eastern Caribbean dollar';
INSERT INTO ccy VALUES ('XCD','Eastern Caribbean dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Eastern Caribbean dollar';
INSERT INTO ccy VALUES ('WST','Samoan tālā','T') ON DUPLICATE KEY UPDATE ccy_symbol='T', ccy_name='Samoan tālā';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('STN','São Tomé and Príncipe dobra','Db') ON DUPLICATE KEY UPDATE ccy_symbol='Db', ccy_name='São Tomé and Príncipe dobra';
INSERT INTO ccy VALUES ('SAR','Saudi riyal','ر.س') ON DUPLICATE KEY UPDATE ccy_symbol='ر.س', ccy_name='Saudi riyal';
INSERT INTO ccy VALUES ('XOF','West African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='West African CFA franc';
INSERT INTO ccy VALUES ('RSD','Serbian dinar','дин.') ON DUPLICATE KEY UPDATE ccy_symbol='дин.', ccy_name='Serbian dinar';
INSERT INTO ccy VALUES ('SCR','Seychellois rupee','₨') ON DUPLICATE KEY UPDATE ccy_symbol='₨', ccy_name='Seychellois rupee';
INSERT INTO ccy VALUES ('SLL','Sierra Leonean leone','Le') ON DUPLICATE KEY UPDATE ccy_symbol='Le', ccy_name='Sierra Leonean leone';
INSERT INTO ccy VALUES ('SGD','Singapore dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Singapore dollar';
INSERT INTO ccy VALUES ('USD','United States dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar';
INSERT INTO ccy VALUES ('ANG','Netherlands Antillean guilder','ƒ') ON DUPLICATE KEY UPDATE ccy_symbol='ƒ', ccy_name='Netherlands Antillean guilder';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('SBD','Solomon Islands dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Solomon Islands dollar';
INSERT INTO ccy VALUES ('SOS','Somali shilling','Sh') ON DUPLICATE KEY UPDATE ccy_symbol='Sh', ccy_name='Somali shilling';
INSERT INTO ccy VALUES ('SLS','Somaliland shilling','Sl') ON DUPLICATE KEY UPDATE ccy_symbol='Sl', ccy_name='Somaliland shilling';
INSERT INTO ccy VALUES ('ZAR','South African rand','R') ON DUPLICATE KEY UPDATE ccy_symbol='R', ccy_name='South African rand';
INSERT INTO ccy VALUES ('RUB','Russian ruble','₽') ON DUPLICATE KEY UPDATE ccy_symbol='₽', ccy_name='Russian ruble';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('SSP','South Sudanese pound','£') ON DUPLICATE KEY UPDATE ccy_symbol='£', ccy_name='South Sudanese pound';
INSERT INTO ccy VALUES ('LKR','Sri Lankan rupee','ரூ') ON DUPLICATE KEY UPDATE ccy_symbol='ரூ', ccy_name='Sri Lankan rupee';
INSERT INTO ccy VALUES ('SDG','Sudanese pound','ج.س.') ON DUPLICATE KEY UPDATE ccy_symbol='ج.س.', ccy_name='Sudanese pound';
INSERT INTO ccy VALUES ('SRD','Surinamese dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Surinamese dollar';
INSERT INTO ccy VALUES ('SEK','Swedish krona','kr') ON DUPLICATE KEY UPDATE ccy_symbol='kr', ccy_name='Swedish krona';
INSERT INTO ccy VALUES ('CHF','Swiss franc','Fr.') ON DUPLICATE KEY UPDATE ccy_symbol='Fr.', ccy_name='Swiss franc';
INSERT INTO ccy VALUES ('SYP','Syrian pound','ل.س') ON DUPLICATE KEY UPDATE ccy_symbol='ل.س', ccy_name='Syrian pound';
INSERT INTO ccy VALUES ('TWD','New Taiwan dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='New Taiwan dollar';
INSERT INTO ccy VALUES ('TJS','Tajikistani somoni','ЅМ') ON DUPLICATE KEY UPDATE ccy_symbol='ЅМ', ccy_name='Tajikistani somoni';
INSERT INTO ccy VALUES ('TZS','Tanzanian shilling','Sh') ON DUPLICATE KEY UPDATE ccy_symbol='Sh', ccy_name='Tanzanian shilling';
INSERT INTO ccy VALUES ('THB','Thai baht','฿') ON DUPLICATE KEY UPDATE ccy_symbol='฿', ccy_name='Thai baht';
INSERT INTO ccy VALUES ('XOF','West African CFA franc','Fr') ON DUPLICATE KEY UPDATE ccy_symbol='Fr', ccy_name='West African CFA franc';
INSERT INTO ccy VALUES ('TOP','Tongan paʻanga','T$') ON DUPLICATE KEY UPDATE ccy_symbol='T$', ccy_name='Tongan paʻanga';
INSERT INTO ccy VALUES ('PRB','Transnistrian ruble','р.') ON DUPLICATE KEY UPDATE ccy_symbol='р.', ccy_name='Transnistrian ruble';
INSERT INTO ccy VALUES ('TTD','Trinidad and Tobago dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Trinidad and Tobago dollar';
INSERT INTO ccy VALUES ('TND','Tunisian dinar','د.ت') ON DUPLICATE KEY UPDATE ccy_symbol='د.ت', ccy_name='Tunisian dinar';
INSERT INTO ccy VALUES ('TRY','Turkish lira','₺') ON DUPLICATE KEY UPDATE ccy_symbol='₺', ccy_name='Turkish lira';
INSERT INTO ccy VALUES ('TMT','Turkmenistan manat','m') ON DUPLICATE KEY UPDATE ccy_symbol='m', ccy_name='Turkmenistan manat';
INSERT INTO ccy VALUES ('USD','United States dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar';
INSERT INTO ccy VALUES ('TVD','Tuvaluan dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Tuvaluan dollar';
INSERT INTO ccy VALUES ('UGX','Ugandan shilling','Sh') ON DUPLICATE KEY UPDATE ccy_symbol='Sh', ccy_name='Ugandan shilling';
INSERT INTO ccy VALUES ('UAH','Ukrainian hryvnia','₴') ON DUPLICATE KEY UPDATE ccy_symbol='₴', ccy_name='Ukrainian hryvnia';
INSERT INTO ccy VALUES ('AED','United Arab Emirates dirham','د.إ') ON DUPLICATE KEY UPDATE ccy_symbol='د.إ', ccy_name='United Arab Emirates dirham';
INSERT INTO ccy VALUES ('GBP','British pound','£') ON DUPLICATE KEY UPDATE ccy_symbol='£', ccy_name='British pound';
INSERT INTO ccy VALUES ('USD','United States dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar';
INSERT INTO ccy VALUES ('UYU','Uruguayan peso','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='Uruguayan peso';
INSERT INTO ccy VALUES ('UZS','Uzbekistani soʻm','сўм') ON DUPLICATE KEY UPDATE ccy_symbol='сўм', ccy_name='Uzbekistani soʻm';
INSERT INTO ccy VALUES ('VUV','Vanuatu vatu','Vt') ON DUPLICATE KEY UPDATE ccy_symbol='Vt', ccy_name='Vanuatu vatu';
INSERT INTO ccy VALUES ('EUR','Euro','€') ON DUPLICATE KEY UPDATE ccy_symbol='€', ccy_name='Euro';
INSERT INTO ccy VALUES ('VES','Venezuelan bolívar fuerte','Bs.F.') ON DUPLICATE KEY UPDATE ccy_symbol='Bs.F.', ccy_name='Venezuelan bolívar fuerte';
INSERT INTO ccy VALUES ('VES','Venezuelan bolívar soberano','Bs.S.') ON DUPLICATE KEY UPDATE ccy_symbol='Bs.S.', ccy_name='Venezuelan bolívar soberano';
INSERT INTO ccy VALUES ('VND','Vietnamese đồng','₫') ON DUPLICATE KEY UPDATE ccy_symbol='₫', ccy_name='Vietnamese đồng';
INSERT INTO ccy VALUES ('XPF','CFP franc','₣') ON DUPLICATE KEY UPDATE ccy_symbol='₣', ccy_name='CFP franc';
INSERT INTO ccy VALUES ('YER','Yemeni rial','ر.ي') ON DUPLICATE KEY UPDATE ccy_symbol='ر.ي', ccy_name='Yemeni rial';
INSERT INTO ccy VALUES ('YUN','Yugoslav dinar','дин.') ON DUPLICATE KEY UPDATE ccy_symbol='дин.', ccy_name='Yugoslav dinar';
INSERT INTO ccy VALUES ('ZMW','Zambian kwacha','ZK') ON DUPLICATE KEY UPDATE ccy_symbol='ZK', ccy_name='Zambian kwacha';
INSERT INTO ccy VALUES ('USD','United States dollar','$') ON DUPLICATE KEY UPDATE ccy_symbol='$', ccy_name='United States dollar';

